### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by torfjelde** [TuringLang/TuringTutorials#110]
Right now there is no handling of redirects. It seems like the way to go is to use https://github.com/jekyll/jekyll-redirect-from, which requires us to change

```yaml
---
title: "Introduction to Turing"
permalink: "/:collection/:name/"
---
```

to

```yaml
---
title: "Introduction to Turing"
permalink: "/:collection/:name/"
redirect_from: "tutorials/0-introduction/"
---
```

The questions is: should this be done in the tutorial itself, i.e. in TuringTutorials, or is this something that we should add programmatically in turing.ml?

Personally I'm leaning towards doing this in TuringTutorials as this is where the renaming happens, making it easier to keep track of changes. At the same time this means that there is a discrepancy between the `permalink` field which is somewhat agnostic to the naming of the folder of the file while `redirect_from` is hard-coded. Even so, IMO it's best to keep track of this in TuringTutorials.

Thoughts?
